language: objective-c
sudo: false
osx_image: xcode6.4
script:
- curl -fsSL https://raw.githubusercontent.com/legoless/Dominus/master/install.sh | sh
env:
  matrix:
  - ACTION=build
  - ACTION=test
  global:
  - SDK=8.4
  - PLATFORM='iphone'
